# FROM --platform=linux/amd64 playwright/chromium:playwright-1.39.0
# FROM selenium/standalone-chrome:latest
FROM wpt-agent

ARG DEBIAN_FRONTEND=noninteractive
ARG NODE_MAJOR=20

USER root

RUN apt purge -y nodejs npm

RUN sudo apt-get update && \
    apt-get install -y ca-certificates curl gnupg
RUN mkdir -p /etc/apt/keyrings
RUN curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg && \
     echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list

RUN apt purge -y libnode-dev

RUN apt-get update && \
    apt-get install nodejs -y