# FROM --platform=linux/amd64 playwright/chromium:playwright-1.39.0
# FROM selenium/standalone-chrome:latest
FROM kasmweb/chromium:1.14.0-rolling

ARG DEBIAN_FRONTEND=noninteractive

USER root

RUN sed -i 's/archive.ubuntu.com/mirrors.aliyun.com/g' /etc/apt/sources.list \
&& sed -i 's/security.ubuntu.com/mirrors.aliyun.com/g' /etc/apt/sources.list

RUN apt-get clean \
    && apt-get update --fix-missing \
    && apt install -y \
    python3 \
    python3-pip \
    imagemagick \
    python3-psutil \
    python3-ujson \
    python3-xvfbwrapper \
    python3-dnspython \
    python3-monotonic \
    python3-tornado \
    python3-fonttools \
    python3-wsaccel \
    ffmpeg \
    sudo \
    wget \
    curl \
    xvfb \
    psmisc \
    net-tools \
    traceroute \
    iproute2 \ 
    software-properties-common \
    libnss3 \
    gnupg2 \
    dnsmasq-base \
    git \
    npm
    # libatk1.0-0 libatk-bridge2.0-0 libcups2 libxkbcommon-x11-0 libxdamage1 libgbm-dev libpangocairo-1.0-0
RUN npm install -g lighthouse
RUN python3 -m pip install -i https://pypi.mirrors.ustc.edu.cn/simple/ psutil

WORKDIR /
RUN rm -rf wptagent && git clone -b master https://github.com/WPO-Foundation/wptagent.git
WORKDIR /wptagent
RUN python3 -m pip install -i https://pypi.mirrors.ustc.edu.cn/simple/ --upgrade --user pip && \
python3 -m pip install -i https://pypi.mirrors.ustc.edu.cn/simple/ --default-timeout=1000 --user -r /wptagent/.github/workflows/requirements.txt

# RUN apt install -y libatk1.0-0 libatk-bridge2.0-0 libcups2 libxkbcommon-x11-0 libxdamage1 libgbm-dev libpangocairo-1.0-0
RUN apt-get install -y dbus sssd-dbus apt-transport-https dbus-user-session dbus-user-session \
    firefox
RUN mkdir -p /var/run/dbus
RUN dbus-daemon --config-file=/usr/share/dbus-1/system.conf --print-address
RUN service dbus start

WORKDIR /wptagent
COPY docker/local/agent/entrypoint.sh /wptagent/entrypoint.sh
ENTRYPOINT bash /wptagent/entrypoint.sh
# CMD python3 wptagent.py -vvvv --xvfb --dockerized --server  http://web/work/ --location Test --key 123456789 --shaper none

